# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_MODE='nerdfont-complete'

# Configure prompt using powerlevel9k
# Note: run the following commands to check the available colors and the set icons
# for code ({000..255}) print -P -- "$code: %F{$code}This is how your text would look like%f"
# 
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs command_execution_time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%f"

POWERLEVEL9K_DIR_HOME_BACKGROUND='006'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='006'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='006'
POWERLEVEL9K_DIR_ETC_BACKGROUND='006'

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='235'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='255'

POWERLEVEL9K_EXECUTION_TIME_ICON='\uF49B'

POWERLEVEL9K_STATUS_OK_BACKGROUND='242'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='005'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='016'

POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_ETC_ICON=''

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='003'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='005'

POWERLEVEL9K_VCS_UNSTAGED_ICON='\uE238'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\uE007'
POWERLEVEL9K_VCS_STAGED_ICON='\uE257'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\uE340'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\uE353'

POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

VIRTUAL_ENV_DISABLE_PROMPT=1
POWERLEVEL9K_PYTHON_ICON='\uF1D0'


# Visual customisation of the second prompt line
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" %{%B%F{009}%}%{%f%F{011}%}%{%f%F{014}%}%{%b%f%} "
